#!/usr/bin/env bash

BACKUP_PATH=${BACKUP_PATH="$HOME/sites-backups"}

current_path=$(dirname $(readlink -f $0))
current_time=$(date +%F_%R:%S)
backup_dir="$BACKUP_PATH/$current_time"

mkdir $backup_dir || (echo "Can't create directory for backups ($backup_dir)" 1>&2 && exit 1)

for site in /etc/apache2/sites-available/*; do
    site_path=$(sed -ne 's/^[[:space:]]*DocumentRoot[[:space:]]\+\([^[:space:]]*\)/\1/p' $site) 
    site_name=$(sed -ne 's/^[[:space:]]*ServerName[[:space:]]\+\([^[:space:]]*\)/\1/p' $site) 

    ([[ ! -d "$site_path" ]] || [[ -f "$site_path/.no-backup" ]]) && continue

    if [[ -z $site_name ]]; then
        echo "Backing up: $site"
    else
        echo "Backing up: $site_name ($site)"
    fi
    echo "Document root: $site_path"

    backup_file=$backup_dir/$site_name\_$current_time.zip

    if  [[ -f "$site_path/configuration.php" ]]; then
        "$current_path/joomla-backup" $site_path $backup_file 1>/dev/null && \
            echo "Ok. Backup was saved to $backup_file"
    else
        zip -ru $backup_file $site_path 1>/dev/null && \
            echo "Ok. Backup was saved to $backup_file"
    fi

    echo 
done
